### ISSUE TITLE
SVGs not loading

### ISSUE THREAD

**Issue by mjmnagy** [sionzee/rollup-plugin-inline-svg#5]
Hi, 

Im having a hard time getting the rollup config to bundle the `SVG`s. Essentially I'm trying to create an icon pack that will allow a user to select an icon and import during runtime. Is this possible using this plugin?

I have tried a lot of plugins and combinations without success.

Directory structure:
dist -> rollup files
src
  - components //Vue  component to import .svg and render (getIcon() -->method catch statement is always being called - Cannot read property 'set' of undefined )
     - icon.vue
  - icons
     - icon types (brand, light etc)
        - icons (.svg)

Repo: https://github.com/mjmnagy/rollup-svg

I apologize if this is out of the scope of the plugin but i am lost
thanks

**Comment by sionzee** [comment]
Hey! Sorry for late response. Seems the email somehow ended in my spam inbox. 
This plugin takes a SVG file which is being imported and converts it to html.

Basically if you import a svg like this:
```typescript
import SVG_FILE from "path/to/file.svg"
```
Then
```
if(SVG_FILE === "<svg attributes>content of the svg</svg>")
```
is true

---

I think you cannot import SVG files dynamically because the rollup doesn't know if it should bundle them. Even if you somehow do it then it is not possible to use this plugin in runtime. So it will fail on import.

I see you are using plugin called "@rollup/plugin-dynamic-import-vars" but it won't help you here.
At runtime you don't have available dev-dependencies.

Anyway there is other workaround for you:
- You should map your SVG files into some object, eg:
```
import SVG1 from "..."
import SVG2 from "..."
import SVGn from "..."

export default {
  "iconA": SVG1,
  "iconB": SVG2,
  "iconN": SVGnm
}
```

Then you can use this object for your Vue component and use dynamic key to load svg files.
